version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando dependencias
      - npm install
  build:
    commands:
      - echo Build Inciando em `date`
      - npm run build
  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
artifacts:
  files:
    - build/**/*